apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
spec:

  replicas: 3
  image: postgres:13.2
  #port: 5432

  #imagePullSecrets:
  #  - name: my-private-docker-repo-secret
  # resources:
  #     limits:
  #       memory: "4Gi"
  #       cpu: "1"
  #     requests:
  #       memory: "2Gi"
  #       cpu: "1"
  database:
    size: 200Mi
    #storageClassName: standard
    #volumeMount: /var/lib/postgres/data

  customConfig: mypostgres-conf
  primary:
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "1"
  replica:
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"

  #failover:
  #  isDisabled: true
  #  promotePod: "mypostgres-3-0"

  #backup:
  #  schedule: "*/1 * * * *"
  #  pvcName: postgres-db-mypostgres-2-0
  #  volumeMount: /tmp/mypostgres

  #scheduler:
  #
  #  affinity:
  #    podAntiAffinity:
  #      preferredDuringSchedulingIgnoredDuringExecution:
  #        - weight: 90
  #          podAffinityTerm:
  #            labelSelector:
  #              matchExpressions:
  #                - key: app
  #                  operator: In
  #                  values:
  #                    - postgres-name
  #            topologyKey: "kubernetes.io/hostname"
  #
  #  tolerations:
  #    - key: group
  #      operator: Equal
  #      value: critical

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: replicationUserPassword

    - name: POSTGRES_MYAPP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mypostgres-secret
          key: myAppUserPassword
