# permissions for end users to view kubegres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubegres-viewer-role
rules:
- apiGroups:
  - kubegres.reactive-tech.io
  resources:
  - kubegres
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubegres.reactive-tech.io
  resources:
  - kubegres/status
  verbs:
  - get
