apiVersion: v1
kind: Secret
metadata:
  name: toto
  namespace: custom
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  myAppUserPassword: myAppUserPsw
